---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: DevopsTest
  region: us-east-2

managedNodeGroups:
  - name: DevOpsTestNodeGrp
    instanceType: m5.large
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    availabilityZones: ["us-east-2a", "us-east-2b"]
    volumeSize: 50
    updateConfig:
      maxUnavailable: 3 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
#    securityGroups:
#      attachIDs: ["sg-1", "sg-2"]
    labels: {role: worker}
    # Note: unmanaged nodegroups (`nodeGroups` field) use a different structure (map[string]string) to express taints
    tags:
      nodegroup-role: worker
#    iam:
#      withAddonPolicies:
#        externalDNS: true
#        certManager: true
